//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using EntityCoreTemplate.Domain.Entities;

namespace Services.Books
{
    public interface IBooksService
    {
        Task<Book> AddAsync(Book book);
        Task<List<Book>> GetAllAsync();
        Task<ListResult<Book>> FilterAsync(PaginationOptions filter);
        Task<Book> GetByIdAsync(long id);
        Task<Book> UpdateAsync(long id, Book book);
        Task<Book> DeleteAsync(long id);
    }
}