//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using EntityCoreTemplate.Domain.Entities;

namespace DataTransferObjects.Books;

public class BookCreationDto
{
	public string Name { get; set; }
	public string Author { get; set; }
	public BookType Type { get; set; }
}
