name: Publish .NET Template (via .nuspec) to NuGet

on:
  push:
    branches:
      - prod

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NuGet CLI
      uses: nuget/setup-nuget@v1

    - name: Pack template with nuget
      run: |
        nuget pack EntityCoreTemplate.nuspec -OutputDirectory ./nupkg
        echo "=== nupkg filelari ==="
        dir ./nupkg

    - name: Push NuGet package
      shell: powershell
      run: |
        $nupkg = Get-ChildItem -Path "./nupkg" -Filter "*.nupkg" | Select-Object -First 1
        if ($nupkg) {
            & $env:NUGET push $nupkg.FullName -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}
        } else {
            Write-Error "nupkg fayli topilmadi"
        }